# Generated by Django 4.0.4 on 2022-05-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_f_name', models.CharField(max_length=32)),
                ('user_l_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('profile_picture', models.BinaryField(blank=True)),
                ('user_dob', models.DateField()),
                ('user_last_access', models.DateTimeField(auto_now_add=True)),
                ('user_active', models.BooleanField(blank=True, default=False)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_addr', models.CharField(max_length=254, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFTValidationApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('nft_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=254, unique=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFTValidationApp.wallet')),
            ],
        ),
    ]
